<?php
/**
 * Federation Clubs Data
 * Official club lists from SCF, NCF, and DCU
 * Shared between club-rf-registration.php and club-rf-spelling.php
 */

// SCF Districts with their registered clubs
$scf_districts = [
    'Bohuslän-Dals Cykelförbund' => [
        '444 Cycling Club',
        'Bokenäs Idrottsförening',
        'Camp Dalsland',
        'Cykelklubben Sundet',
        'Framtidens Idrotts Klubb',
        'Friluftsfrämjandet Bengtsfors',
        'Munkedals Skid & Cykelklubb',
        'OK Kroppefjäll',
        'Skidklubben Granan',
        'Strömstad Cykelklubb',
        'Svanesunds Gymnastik o Idrottsförening',
        'Team Swedemount Sports Club',
        'Uddevalla Cykelklubb',
        'Åmåls Cykelamatörer'
    ],
    'Dalarnas Cykelförbund' => [
        'Biketown Cycling Club',
        'Bjursås Idrottsklubb',
        'Borlänge Cykelklubb',
        'Brudpiga Roddklubb',
        'CK Uven',
        'CK Vansbro Mtb',
        'CSK Ludvika',
        'Cykelklubben Natén Säter',
        'Cykelklubben Soldi',
        'Dala-Järna Idrottsklubb',
        'Falu Cykelklubb',
        'Idrottsföreningen Vulcanus',
        'Idrottsklubben Jarl Rättvik',
        'Lima Idrottsförening',
        'Malungs Cykelklubb',
        'ML Sports Club',
        'Mora Cykel Klubb',
        'Perbellum Sportsällskap',
        'Rembo Idrottsklubb',
        'Sollerö Idrottsförening',
        'Sågmyra Skidklubb',
        'Sälens Idrottsförening',
        'Särna Cykelklubb',
        'Team KBK Bikes Cykelklubb',
        'Velodrom Cykelklubben',
        'Älvdalens CK'
    ],
    'Gästriklands Cykelförbund' => [
        'Gogagaski Cycle Club',
        'Gästrike Cup MTB Förening',
        'Gävle Cykelamatörer',
        'Hofors AIF Skid och Cykelklubb',
        'Järbo Idrottsförening',
        'Orienteringsklubben Hammaren',
        'Sandvikens Cykelklubb',
        'Storviks Idrottsförening',
        'Årsunda Idrottsförening'
    ],
    'Göteborgs Cykelförbund' => [
        'Aktivitus Sports Club',
        'Ale 90 Idrottsklubb',
        'Angered Cykelförening',
        'Cykelklubben Lygnens Venner',
        'Cykelklubben Master',
        'Cykelklubben Rävlanda',
        'Giro Cycle Club',
        'Göteborgs Atlet- & Triathlonsällskap',
        'Göteborgs Cykelklubb',
        'Göteborgs Polismäns IF',
        'Göteborgs Stigcyklister',
        'Hisingens Cykelklubb',
        'Kungälvs Cykelklubb',
        'Lerums Cykelklubb',
        'Mölndals Cykelklubb',
        'Partille Cykelklubb',
        'Partille Trialklubb',
        'Rendezvous Cycling Club',
        'Sävedalens Cykelklubb',
        'Team Hestra-Advokat Cycling Club',
        'Team Kungälv Idrottssällskap',
        'Torslanda Cykelklubb',
        'Umara Sports Club'
    ],
    'Hallands Cykelförbund' => [
        'Bukten Mountainbike Klubb',
        'Cogheart Cycle Club Varberg',
        'Cykelklubben Bure',
        'Cykelklubben Wano',
        'Falkenbergs Cykelklubb',
        'Halmstad Mountainbikeklubb',
        'Halmstads Cykelklubb',
        'Hawkhills Trialklubb',
        'Idrottsföreningen Rigor',
        'Kungsbacka BMX-Klubb',
        'Kungsbacka Cykelklubb',
        'Kungsbackacyklisten Idrottsförening',
        'Laholmscyklisten Cykelklubb',
        'Nordic Sports Academy Sports Club',
        'Rooster Club Varberg Idrottsförening'
    ],
    'Hälsinglands Cykelförbund' => [
        'Bollnäs Cykelklubb',
        'Edsbyns Skidklubb',
        'Hudik Triathlon Klubb',
        'Hälsinglands Sportklubb',
        'IFK Söderhamn',
        'Järvsö Bergscykelklubb'
    ],
    'Jämtland-Härjedalens Cykelförbund' => [
        'Brunflo Idrottsförening',
        'Edelweiss Cykelklubb',
        'Frösö Idrottsförening',
        'Funäsdalens Idrottsförening',
        'Genvalla Idrottsförening',
        'Lofsdalens Sportklubb',
        'Sockertoppen Idrottsförening',
        'Svegs Idrottsklubb',
        'Vemdalens Idrottsförening',
        'Åre Bergscyklister',
        'Åsarna Idrottsklubb',
        'Östersunds Cykelklubb'
    ],
    'Norrbottens Cykelförbund' => [
        'Befastonabike cykelklubb',
        'Bodens Cykelklubb',
        'Dundret MTB',
        'Föreningen Luleå Terrängcyklister',
        'Gammelgårdens Idrottsförening',
        'Gällivare Endurance Club',
        'IFK Arvidsjaur Skidor',
        'Kiruna Fjällcyklister',
        'Luleå Cykelklubb',
        'Nybyns Cykelklubb',
        'Orienteringsklubben Renen',
        'Pite MTB-förening',
        'Råneå Skidklubb'
    ],
    'Skånes Cykelförbund' => [
        'Beijers Coaching Cykel Klubb',
        'CK Öresund',
        'Cykelklubb Pedali Skurup',
        'Cykelklubben Barriär',
        'Cykelklubben C4',
        'Cykelklubben Fix',
        'Cykelklubben Lunedi',
        'Cykelklubben Ringen',
        'Cykelklubben Wheels of Carlshamn',
        'Engelholms Bmx-klubb',
        'Eslövs Cykelklubb',
        'Friluftsklubben Trampen',
        'Frosta Multisport',
        'Heleneholms Idrottsförening',
        'Hässleholms Cykelklubb',
        'Höllviken Cykelklubb',
        'Hörby CykelKlubb',
        'Idrottsklubben Vinco',
        'Karlskrona Cykelklubb',
        'Klubben Cyklisten',
        'Knutstorp Cykel- och Motorklubb',
        'Landskrona Cykelklubb',
        'Malmö BMX Racing',
        'Malmö Cykelcross Klubb',
        'Malmö Cykelklubb',
        'MIND Triathlon Sports Club',
        'Olofströms Fritidsklubb',
        'Peak Vélo CK',
        'Roslins Cykelklubb',
        'Staffanstorp Cykelklubb',
        'Sölvesborgs Cykel & Sportklubb',
        'Team Albert cykelklubb',
        'X-CUP Cykelklubb',
        'Ystad MTB Cykelklubb',
        'Åhus Cykelklubb',
        'Åstorps Cykelklubb',
        'Örestadscyklisterna Idrottsförening',
        'Örkelljunga Outdoors Klubb'
    ],
    'Smålands Cykelförbund' => [
        '338 Småland Triathlon & MF',
        'Abloc Idrottsförening',
        'Actionsport Unite IF',
        'Anderstorps Orienteringsklubb',
        'Bankeryds Skid o Motionsklubb',
        'Bauer Endurance Club',
        'Borgholm Cykelklubb',
        'Bottnaryds Idrottsförening',
        'Braås Gymnastik O IF',
        'Brittatorps Träningsklubb',
        'Burseryds Idrottsförening',
        'Cykelklubben Grand La Coupe',
        'Cykelklubben Wimer',
        'Eksjö Cykelklubb',
        'Elmhults Sports Club',
        'Emmaboda Verda OK',
        'Friluftsfrämjandets Lokalavd i Värnamo',
        'Föreningen Wexiö Velo',
        'Glasrikets Runningclub Nybro',
        'Gnosjö Friluftsklubb',
        'Gotland Grand National Sports Club',
        'Gränna-Bygdens OK',
        'Highland Cycling Club',
        'Hjortens Sportklubb',
        'Hultsfreds Löparklubb',
        'Idrottsklubben Habocyklisterna',
        'IF Hallby Skid o Orienteringsklubb',
        'IFK Sävsjö',
        'IKHP Huskvarna Idrottsklubb',
        'JHWC Cykelklubb',
        'Jönköpings Cykelklubb',
        'KA 3 Idrottsförening',
        'Kalmar Cykelklubb',
        'Kalmar Running Club Triathlon',
        'Lammhult Cyklisterna',
        'Malmbäcks Idrottsförening',
        'Markaryds Friluftsklubb',
        'Mix Sports Club',
        'Möre Bollklubb',
        'Nässjö Cykelklubb',
        'Orienteringsklubben Vivill',
        'Orrefors Idrottsförening',
        'Oskarshamns Cykelklubb',
        'Ringmurens Cykelklubb',
        'Sandhems Idrottsförening',
        'Skid- och orienteringslöparna Tranås',
        'Skillingaryds Frisksportklubb',
        'Sportson Cykelklubb Jönköping',
        'Team Kalmarsund Cykelklubb',
        'Tenhults Skid o Orienteringsklubb',
        'Tjust Bike o Running Club',
        'Tranås Cykelklubb',
        'Vaggeryds Skid o Orienteringsklubb',
        'Värnamo Cykelklubb',
        'Växjö Stigcyklister',
        'Ålems Cykelklubb'
    ],
    'Stockholms Cykelförbund' => [
        '58&fam Racing Club',
        'Athletic Club Salt Lake',
        'Atlas Copco Idrottsförening',
        'AXA Sports Club',
        'Baroudeur Fietsclub',
        'Bike Adventure Cycling Club',
        'Brottby Sportklubb',
        'Capital Bikepark Locals CK',
        'Cykelklubb La Chemise.se',
        'Cykelklubben Falken',
        'Cykelklubben Nollåtta',
        'Cykelklubben Valhall',
        'Djurgårdens IF Cykelförening',
        'Echelon Cycling and Triathlon Club',
        'Ekerö MTB',
        'Evolite Cycling Club',
        'Fredrikshofs IF Cykelklubb',
        'Förening Rocket Racing Sweden',
        'Hammarby IF Cykelförening',
        'Ingarö Idrottsförening',
        'Järfälla Cykel Klubb',
        'Kia Merida racing team Cykelklubb',
        'Lidingö Cykelklubb',
        'Lucky Sport Cycling Club',
        'Länna Sport Cykelklubb',
        'Mountainbikeskolan CK',
        'MTB Täby Mountainbikeklubb',
        'Muskö Idrottsförening',
        'Pain Free Power Athletic Club',
        'Reaktion Cycling Club',
        'Ryska Posten SK',
        'Saltsjöbadens Cykelklubb',
        'She Rides Cykelklubb',
        'She Rise Athletic Club',
        'Sigge Cykel Klubb',
        'Specialized Concept Store Cykelklubb',
        'Spårvägen Cykelförening',
        'Sthlm Bike Cykelklubb',
        'Stockholm City Triathlon Club',
        'Stockholm Cykelklubb',
        'Stockholm Multisport Klubb',
        'Sumo Cycling Club',
        'Sveaskogs Idrottsförening',
        'Södertälje Cykelklubb',
        'Södertälje-Nykvarn Orienteringsförening',
        'Södertörns Cykelklubb',
        'Team Jarla Cykelklubb',
        'Team Snabbare Idrottsförening',
        'Team Utan Gränser Cykelklubb',
        'Terrible Tuesdays Athletic Club',
        'Trailstore Collective BC',
        'Tullinge Sportklubb',
        'Tyresö Cykelklubb',
        'Vallentuna Cykelklubb',
        'Waxholm Cykelklubb',
        'Velocipedföreningen Punschrullen',
        'Värmdö Cykelklubb',
        'Älvsjö Bmx-klubb',
        'Ängby cycling club'
    ],
    'Södermanlands Cykelförbund' => [
        'Cykelklubben Ceres',
        'Cykelklubben Dainon',
        'Eskilstuna Cykelklubb',
        'Eskilstuna Idrottsklubb',
        'Oxvretens Skidklubb',
        'Strängnäs Cykelklubb',
        'Team Average Athletic Club',
        'Team Sméstan Cykelklubb',
        'Trosabygdens Orienteringsklubb',
        'Vingåkers CK',
        'Ärla Idrottsförening'
    ],
    'Upplands Cykelförbund' => [
        'BAUHAUS Sportklubb',
        'Björklinge Sportförening',
        'Bålsta Cykelklubb',
        'Cykelklubben Norrtälje',
        'Cykelklubben Stabil',
        'Cykelklubben Uni',
        'Enköpings Cykelklubb',
        'Heby Allmänna Idrottsförening',
        'Häverödals Sportklubb',
        'Idrottsföreningen Mantra Sport',
        'IK Rex',
        'Knivsta Cykelklubb',
        'Marma Sportklubb',
        'Motorklubben Orion',
        'Månkarbo Idrottsförening',
        'Märsta BMX Club-83',
        'Rimbo Skid o Orienteringsklubb',
        'Shimano Nordic Racing Cykelklubb',
        'Sigtuna Märsta Arlanda Cykelklubb',
        'Sigtuna Sports Club',
        'SMK Uppsala',
        'Storvreta Idrottsklubb',
        'Tierps Cykelklubb',
        'Upplands-Ekeby Idrottsförening',
        'Upsala Cykelklubb',
        'Womens Bikejoy Cykelklubb',
        'Öregrunds Idrottsklubb',
        'Östervåla Idrottsförening',
        'Östra Aros Cykelklubb'
    ],
    'Värmlands Cykelförbund' => [
        'Arvika Cykelklubb',
        'Arvika Idrottssällskap',
        'Carba Sports Club',
        'Cykelklubben Filip',
        'Ekshärads Cykelklubb',
        'Grava Skidklubb',
        'I 2 Idrottsförening',
        'Jössefors Idrottsklubb',
        'Karlskogacyklisterna',
        'KONG Arrangörs- och Idrottsförening',
        'Kristinehamns Cykelklubb',
        'Mattila Idrottsklubb',
        'Orienteringsklubben Tyr',
        'Skidklubben Bore Torsby',
        'Skoghalls Cykelklubb-Hammarö',
        'Solsta Cykelklubb',
        'South Wermland Sports Club',
        'Sunne DH & Enduro Klubb',
        'Säffle Idrottsklubb',
        'Team Skoglöfs Bil Idrottsförening',
        'Värmullsåsens Mountainbike & Enduro Klubb',
        'Västra Ämterviks Idrottsförening'
    ],
    'Västerbottens Cykelförbund' => [
        'Bergsbyns Sportklubb',
        'Burträsk aktivitetsförening',
        'Bygdeå Gymnastik Idrottsförening',
        'Föreningen Bygdsiljumsbacken',
        'Föreningen Cykelintresset',
        'Gimonäs Cykelklubb',
        'Lycksele Idrottsförening',
        'Lögdeå Sportklubb',
        'Norrlandscyklisterna Idrottsklubb',
        'Obbola Idrottsklubb',
        'Skellefteå AIK Cykelklubb',
        'Stensele Sportklubb',
        'Tavelsjö Allmänna Idrottsklubb',
        'Team UV Idrottsklubb',
        'Tough Training Group Umeå Idrottsförening',
        'Wattfabriken CK',
        'Vännäs Cykelklubb'
    ],
    'Västergötlands Cykelförbund' => [
        'Alingsås Sportsclub',
        'Alliansloppet Skidklubb',
        'Bollekollen sportklubb',
        'Borås Cykelamatörer',
        'Borås Gymnastik o Idrottsförening',
        'Cycling Club 22',
        'Cykelklubben Olympic',
        'Cykelklubben U6',
        'Cykelklubben Wänershof',
        'Falköpings Cykelklubb',
        'Fritsla Vinter Idrottsklubb',
        'Föreningen 7h ParaAlpint',
        'Gånghester Cykelklubb',
        'Herrljunga Cykelklubb',
        'Hjo Velocipedklubb',
        'Hunneberg Sport och Motionsklubb',
        'Hyssna Idrottsförening',
        'IK Trasten',
        'Kesberget Bikepark CK',
        'Kinds Go Green Cykelklubb',
        'Kvänums Idrottsförening',
        'Lidköpings Cykelklubb',
        'Lindgren Racing Cyclingclub',
        'Långareds Boll o Idrottssällskap',
        'Mariestadcyklisten',
        'Serneke Allebike Cykelklubb',
        'Skara Cykelklubb',
        'Skövde Cykelklubb',
        'Tibro Cykelklubb',
        'Tidaholms Cykelamatörer',
        'Tranemo Cykelsällskap',
        'Tre Berg Cykelklubb',
        'Trollhättans Skid o Orienteringsklubb',
        'Träningskonsulten Sports Club',
        'Töreboda Cykelklubb',
        'Ulricehamns Cykelklubb',
        'West Heath Sportsclub',
        'Vettlösa Cykelklubb',
        'Vincents Idrottsförening',
        'Vårgårda Cykelklubb',
        'Västgötaloppsföreningen'
    ],
    'Västernorrlands Cykelförbund' => [
        'Alnö Race Team Föreningen',
        'Cykelklubben Örnen',
        'Drakstadens Sub Sport Klubb',
        'Föreningen Höga Kusten Cyklisterna',
        'Härnösands Cykelklubb',
        'Northern XC Sportsclub',
        'Resele Idrottsförening',
        'Sundsvallscyklisterna'
    ],
    'Västmanlands Cykelförbund' => [
        'Fagersta Södra Idrottsklubb',
        'Föreningen Hallsta Mountainbike',
        'Gäddeholm Stigcyklister',
        'IFK Sala',
        'Kungsörs Sportklubb',
        'Köpings Cykelklubb',
        'Medåkers Idrottsförening',
        'Norbergs Cykelklubb',
        'Ramnäs Cykelklubb',
        'Sala Cykelklubb',
        'Skultuna Allmänna Idrotts Klubb',
        'Västerås Cykelklubb'
    ],
    'Örebro Läns Cykelförbund' => [
        'Almby Idrottsklubb',
        'Cykelklubben Armkraft',
        'Cykelklubben Kultur',
        'Föreningen BBR Sports',
        'Grythyttans Cykel Klubb',
        'Hjulsjö Byförening Löparklubb',
        'Kilsmo Idrottsklubb',
        'Kopparbergs Cykelklubb',
        'Kumla Skidförening',
        'Laxå Cykelklubb',
        'Lekebergs Idrotts Förening',
        'Lindecyklisterna',
        'Ramsbergs Idrottsförening',
        'Sörbybackens Kamratförening',
        'Åsbro Gymnastik O IF'
    ],
    'Östergötlands Cykelförbund' => [
        'Bistro Cycling Club',
        'Borensbergs IF Sportklubb',
        'Boxholm-Ekeby Skidklubb',
        'Cykelföreningen Tajts MTB',
        'Cykelklubben Antilopen',
        'Cykelklubben Hymer',
        'Cykelklubben SubXX',
        'Finspångs Cykelamatörer',
        'Föreningen Vadstena Cykel',
        'Godegårds Skidklubb',
        'Idrottsklubben Nocout.se',
        'Kisa Sportklubb',
        'Klubb Team LeWa Sport',
        'Kolmårdens Mountainbike Klubb',
        'Mera Lera Mountainbikeklubb',
        'Mjölby Cykelklubb',
        'Motala AIF Cykelklubb',
        'Norrköpings Skidklubb',
        'Sya Skidklubb',
        'Söderköpings Skidklubb',
        'Vreta Skid o Motionsklubb',
        'Åtvidabergs Idrottsförening'
    ]
];

// Norwegian Cycling Federation (NCF) clubs
$ncf_clubs = [
    'Aaby CK',
    'Aalgaard Sykkel & Spaserlaug',
    'Ådal I.L.',
    'Åfjord Idrettslag',
    'Ålen Idrettslag',
    'Ålesund og Omegn Cykleklubb',
    'Andebarkji Terrengsykkelklubb',
    'Andørja Sportsklubb',
    'Aremark Bmxklubb',
    'Aremark Idrettsforening',
    'Arendal Cykleclub',
    'Arna Sykleklubb',
    'Aron Sportsklubb',
    'Åsane Cykle Klubb',
    'Asker Cykleklubb',
    'Åskollen Sykkelklubb',
    'Askøy Sykkel- og Triathlonklubb',
    'Åslia Skilag',
    'Aukra Sykkelklubb',
    'Austevoll Sykkelklubb',
    'Austrått Sykkelklubb',
    'Bagn Idrettslag',
    'Bamble Idrettsforening',
    'Bardu Idrettslag',
    'Bardufoss og Omegn Idrettsforening',
    'Bærum og Omegn Cykleklubb',
    'Bærums Verk Cykleklubb',
    'Bergen Cykleklubb',
    'Bergen Mountainbikeklubb',
    'Bergen Triathlon Club',
    'Berlevåg Turn og Idrettsforening',
    'BI Athletics',
    'Bindal Sykleklubb',
    'Binges Sihkkelsearvi- Binges Cycleklubb',
    'Bingsfoss Sykkelklubb',
    'Biri Idrettslag',
    'Birkenes Idrettslag',
    'Bjørkelangen Sportsforening',
    'Bjørndal Idrettsforening',
    'Blaker IL',
    'Blindleia Cykleklubb',
    'Bodø Cykleklubb',
    'Bodø Freeride Team',
    'Bodø Terrengsykkelklubb',
    'Bogafjell Sykleklubb',
    'Bokn Sykkelklubb',
    'Borgen IL',
    'Bratt sykkelklubb',
    'Breimsbygda IL',
    'Brønnøy Sykkelklubb',
    'Brøttum Idrettslag',
    'Brumunddal Sykleklubb',
    'Bryne Cykleklubb',
    'Bryne Triatlonklubb',
    'Bunes Idrettslag',
    'Burfjord Idrettslag',
    'Bygdø Idrettslag',
    'Bykle Idrettslag',
    'Christiania Velociped klubb',
    'CK Elverum',
    'CK Jarlsberg',
    'Ck Nor- Melhus',
    'CK Øst',
    'CK Toten',
    'CK Valdres',
    'CK Victoria',
    'Cykle-Klubben Henie',
    'Cykleklubben Haugaland',
    'Cykleklubben Nittedal',
    'Cykleklubben Sotra',
    'Dal Idrettslag',
    'Dalane Sykleklubb',
    'Dale Idrettslag',
    'Dirdal Idrettslag',
    'Dølemo Idrettslag',
    'Drammen Cykleklubb',
    'Driv Idrettslag',
    'Drøbak-Frogn Idrettslag',
    'Eidanger Idrettslag',
    'Eide Idrettslag',
    'Eidfjord Idrettslag',
    'Eidsvoll Sykkelklubb',
    'Eiker Cykleklubb',
    'Eina Sportsklubb',
    'Engerdal SK',
    'Eresfjord Idrettslag',
    'Fana Idrettslag',
    'Fannefjord Sykkelklubb',
    'Farsund Sykleklubb',
    'Fauske IL Sykkel',
    'Feiring Idrettslag',
    'Fet Skiklubb',
    'Fevik & Omegn Cycle Club',
    'Fiskeklev og Omegn Landeveisklub',
    'Fiskum Idrettslag',
    'Fitjar Idrettslag',
    'Fjellfoten Sykkelklubb',
    'Flekkefjord Sykkelklubb',
    'Flora Cykleklubb',
    'Follafoss Idrettslag',
    'Follo Sykkelklubb',
    'Fosen Sykkelklubb',
    'Fossum Idrettsforening',
    'Førde Cykleklubb',
    'Fredrikstad Sykkelklubb',
    'Froland Sykkelklubb',
    'Frøya og Hitra Sykkelklubb',
    'FTT Oslo Sykkelklubb',
    'Fusa Sykkelklubb',
    'Gauldal Sykleklubb',
    'Geilo Idrettslag',
    'Gjerdrum Idrettslag',
    'Gjerstad Idrettslag',
    'Glåmdal Sykleklubb',
    'Glitre Offroad Klubb',
    'Grenland Sykleklubb',
    'Gressvik Bmx-Klubb',
    'Gresvik IF',
    'Grimstad Sykleklubb',
    'Gruvelia SK',
    'Grytøy Idrettslag',
    'Gui Sportsklubb',
    'Gulsjøen Sykkelklubb',
    'Hadeland Cykleklubb',
    'Hafjell Freeride Klubb',
    'Hafrsfjord Sykkelklubb',
    'Halden Cykleklub',
    'Halden Skiklubb',
    'Hamar Cykleklubb',
    'Hamarøy Idrettslag',
    'Hammerfest Sykkelklubb',
    'Haram Cykleklubb',
    'Hardanger Sykkelklubb',
    'Harstad Cykleklubb (Hck)',
    'Hasle-Løren Idrettslag',
    'Haugesund triatlonklubb',
    'Heming Idrettslaget',
    'Hemne Sykkelklubb',
    'Hemsedal Idrettslag',
    'Herkules Sykkel',
    'Hessdalen Idrettslag',
    'Hobøl Idrettslag',
    'Hol Idrettslag',
    'Holmenkollen Cykleklubb',
    'Holmestrand Sykkelklubb',
    'Horten og Omegn Cykleklubb',
    'Høland Idretts- og ungdomslag',
    'Høybråten og Stovner IL',
    'Hurdal Idrettslag',
    'Hustadvika Sportsklubb',
    'Idd Sportsklubb',
    'Idrettsforeningen Birkebeineren',
    'Idrettsforeningen Sturla',
    'Idrettsklubben Hero',
    'Idrettslaget Frea',
    'Idrettslaget Jardar',
    'Idrettslaget Polarstjernen',
    'Idrettslaget Skade',
    'Idrettslaget Sverre',
    'If Eiker Kvikk',
    'IF Frøy',
    'IF Klypetussen',
    'IL Norodd',
    'IL Splint',
    'Ishavsbyen Sykkel',
    'Jægervatnet Idrettslag',
    'Karasjok Sykkelklubb',
    'Kirkenes cykleklubb',
    'Kjekkas Idrettsforening',
    'Kjose Idrettslag',
    'Klepp BMX',
    'Klepp Cykle Club',
    'Kloppa offroadklubb',
    'Kløfta Idrettslag',
    'Kolbotn Sykkelklubb',
    'Kongsberg Idrettsforening',
    'Kongsveien Cykleklubb',
    'Konnerud Idrettslag',
    'Kragerø Og Omegn Sykkelklubb',
    'Kristiansands Cykleklubb',
    'Krokskogen Cykleklubb',
    'Kvam Idrettslag',
    'Kvås Idrettslag',
    'Kvinesdal Sykkelklubb',
    'Kvinnherad Sykkelklubb',
    'Land Cykleklubb',
    'Langesund Sykle- og triathlonklubb',
    'Leirfjord Idrettslag',
    'Lillehammer Cykleklubb',
    'Lillestrøm Sykkelklubb',
    'Lofoten Sykkelklubb',
    'Lødingen Sykkelklubb',
    'Lørenskog Cykleklubb',
    'Lund Cykleklubb',
    'Lundersæter Idrettslag',
    'Luster Sykkelklubb',
    'Lye Idrettslag',
    'Lysaker Sportsklubb',
    'Måløy Idrettslag',
    'Malvik Idrettslag',
    'Mandal Cykleklubb',
    'Manndalen Ungdoms og Idrettslag',
    'Matrand Idrettslag',
    'Meløy Ski- & Sykkelklubb',
    'MILTON Larvik Sportsklubb',
    'Mjølkerampa Sykkelklubb – Trøgstad',
    'Modum Cykleklubb',
    'Molde Cykleklubb',
    'Morsa Sykkelklubb',
    'Mosjøen og Omegn Cycleklubb',
    'Moss BMX Club',
    'Moss Cykle Klubb',
    'Mysen Idrettsforening',
    'Namdal Sykkelklubb',
    'Nanset Idrettsforening',
    'Narvik Cykleklubb',
    'Nærbø Sykle Klubb',
    'Nea Cykleklubb',
    'Nerskogen Idrettslag',
    'Nes Sportsklubb',
    'Nes Sykkelklubb',
    'Nesbyen Idrettslag',
    'Nesodden Sykkelklubb',
    'Nidaros Sykkelklubb',
    'Nitelva CK',
    'NOR Cykleklubb',
    'Nordbygda / Løten Ski',
    'Nordhordland Sykkelklubb',
    'Nordlysbyen Sykkel',
    'Nordreisa Idrettslag',
    'Norefjell Cykleklubb',
    'Norges Handelshøyskoles Idrettsforening',
    'Notodden Sykleklubb',
    'NTNUI',
    'Nymark Idrettslag',
    'Odal Sykkelklubb',
    'Odda Idrettslag',
    'Olden Idrettslag',
    'Onsøy Cykleklubb',
    'Oppdal Sykkelklubb',
    'Orkla Cykleklubb',
    'Orstad Bmx Klubb',
    'Oslo Politis Idrettslag',
    'Oslo sykleklubb',
    'Oslofjord triatlon',
    'Oslostudentenes Idrettsklubb',
    'Otra IL',
    'Ottadalen Sykkelklubb',
    'Ottestad Idrettslag',
    'Ølen Idrettslag',
    'Ørskog Idrottslag',
    'Ørsta Sykkelklubb',
    'Østerbo Idrettsforening',
    'Østmarka Idrettslag',
    'Øyer/Tretten Idrettsforening',
    'Paragrafrytterne Sykkelklubb Bamble',
    'Porsanger Cykleklubb',
    'Rå CK',
    'Råde BMX Klubb',
    'Rakkestad Sykkelklubb',
    'Rana Sykkelklubb',
    'Randaberg Sykkelklubb',
    'Ranheim Sykkelklubb',
    'Raufoss Og Gjøvik Sykkelklubb',
    'Rauma Sykkelklubb',
    'Raumerrytter SK',
    'Re Sykkelklubb',
    'Rena Idrettslag',
    'Rennebu Idrettslag',
    'Rennesøy Sykleklubb',
    'Retro Skansen Cykleklubb',
    'Ringerike Sykkelklubb',
    'Romeriksåsen Sykkelklubb',
    'Romsås Idrettslag',
    'ROS IL',
    'Røa Allianseidrettslag',
    'Røldal Idrettslag',
    'Røros Idrettslag',
    'Røyken Cykleklubb',
    'Ryen og Omegn Cykleklubb',
    'Ryfylke Sykkelklubb',
    'S. Høland Idretts- og Ungdomslag (shiul)',
    'Sagene Idrettsforening',
    'Sand Idrettslag',
    'Sandane Sykkelklubb',
    'Sande Sportsklubb',
    'Sandefjord Sykleklubb',
    'Sandnes BMX',
    'Sandnes Sykleklubb',
    'Sandnessjøen og Omegn Cykleklubb',
    'Sandvika Cykle Club',
    'Sarpsborg Sykleklubb',
    'Sauda Sykkelklubb',
    'Savalen Sykkelklubb',
    'Senja Cykleklubb',
    'Senja Sportsklubb',
    'Siggerud Idrettslag',
    'Sirbmá- Sirma Il',
    'Skagerrak Sportsklubb',
    'Skarphedin IL',
    'Skibotn Idrettslag',
    'Skiptvet IL',
    'Skjeberg Cykleklub',
    'Skogn Idrettslag',
    'Smaalenene Sykkelklubb',
    'SOGN CYKLEKLUBB',
    'Soknedalen Idrettslag',
    'Sola BMX',
    'Sola Cykleklubb',
    'Solør Cykleklubb',
    'Solum BMX',
    'Soon Cykleklubb',
    'Søgne Cykleklubb',
    'Søre Osen Idrettslag',
    'Sørum Idrettslag',
    'Sportsklubben Ceres',
    'Sportsklubben Rye',
    'Stabekk Sykkelklubb',
    'Stathelle og Omegn Idrettslag',
    'Stavanger Sykle Klubb',
    'Stavanger Triathlonklubb',
    'Steinkjer Cykleklubb',
    'Stiftstaden Sykkelklubb',
    'Stjørdals-Blink IL',
    'Stokmarknes Idrettslag',
    'Stord Sykleklubb',
    'Stovnerkameratene',
    'Støren Cykleklubb',
    'Stranda Sykkelklubb',
    'Stryn Turn og Idrettslag',
    'Sula Sykkelklubb',
    'Suldal Sykkelklubb',
    'Sunnan Cykle Klubb',
    'Sunnhordland Sykkelklubb',
    'Svarstad Idrettslag',
    'Svelvik Sykleklubb',
    'Sviland BMX',
    'Sykkelklubben Skar Oslo',
    'Sykkylven Sykkelklubb',
    'Sykleklubben Lyngdal & Omegn',
    'Tambarskjelvar Idrettslag',
    'Tangen Watt og Oksygen Cykleklubb',
    'Tasta & omegn sykkelklubb',
    'Tinden J Cycleklubb',
    'Tofte Fremad Idrettsforening',
    'Torshov Sykkelklubb',
    'Toten-Kranken Cykleklubb',
    'Tømmerholt Idrettslag',
    'Tønsberg Cykkelklubb Tck',
    'Trollheimen Sykkelklubb',
    'Tromsø Cykleklubb',
    'Trondhjems Velocipedklub',
    'Trysil Sykkelklubb',
    'Tryvann Cykleklubb',
    'Tverrelvdalen Idrettslag',
    'Ullensaker Cykleklub',
    'Ullevål Sykkelklubb',
    'Ulriken Velocipedklubb',
    'Ulstein og Omegn Sykkelklubb',
    'Valle Idrottslag',
    'Vang Skiløperforening',
    'Varanger Sportsklubb',
    'Varhaug Idrettslag',
    'Vårsol Velocipedclub',
    'Vegårshei Idrettslag',
    'Vennesla og omegn Cykleklubb',
    'Vest CK',
    'Vestby Sykkelklubb',
    'Vesterålen Sykkelklubb',
    'Vestkant Trial',
    'Vestnes-Varfjell Idrettslag',
    'Vestre Aker Sykkelklubb',
    'Vestre Slidre Idrettslag',
    'Vigesaa Sykleklubb',
    'Vigrestad Sykkelklubb',
    'Vind Idrettslag',
    'Vindafjord Idrettslag',
    'Vinje Idrottslag',
    'Vinstra Idrettslag',
    'Voss Mtb-Klubb',
    'Voss Sykleklubb',
    'Vossevangen Cykleklubb',
    'You Never Bike Alone SK, Bærum'
];

// DCU (Danmarks Cykle Union) clubs - organized by district
$dcu_districts = [
    'Distrikt Jylland/Fyn' => [
        'Aalborg Cykle-Ring',
        'Aalborg Cykle-Ring Motion',
        'Aalborg Mountainbikeklub',
        'Aarhus Cyklebane',
        'Aarhus MTB',
        'Aarhus Studenternes Cykelklub',
        'Aars BMX Klub - Lynet',
        'Aarup Motions Cykle Klub',
        'Ærø Cykle Motion CC Flying Heroes',
        'Agerskov Cykel Klub af 1991',
        'Askov Mudeaters',
        'Assentoft Cykelmotion',
        'Billund Cykelmotion',
        'Bjerggedernes Cykelklub',
        'Bjerringbro BMX Klub',
        'BMX Limfjord',
        'Bogense Cykelklub',
        'Bording Cykel Motion',
        'Børkop Motion Cyklister',
        'Bov Cykle Club',
        'Brande Motion',
        'Breakaway Cycling Club',
        'Bredballe Idrætsforening',
        'Broby Idrætsforening',
        'Brønderslev Motions Cykelklub',
        'Brørup Cykel Klub',
        'Christiansfeld Cykelmotion',
        'Cycling DS',
        'Cycling Langeland',
        'Cykel Klubben Aars',
        'Cykel Klubben Djurs',
        'Cykel Motion Biersted',
        'Cykelglæden',
        'Cykelmotion Viborg',
        'Cykle Clubben Hjørring',
        'Cykle Klubben Aarhus',
        'Cyklemotion Odense',
        'Cyklemotion Sønderborg',
        'Cykling Odense',
        'Danfoss Cykel Klub',
        'Dansk Håndcykelklub',
        'Distrikt Jylland Fyn',
        'Dragon BMX',
        'Dronninglund Motions Ck',
        'eCykle Klub Danmark',
        'ED Elite',
        'Elev-Nye Idrætsforening - Cykling',
        'Ellum BMX Klub',
        'Esbjerg Cykle Motion',
        'Esbjerg Cykle Ring Sport af 1919',
        'Faaborg Sport og Motion',
        'Falcon BMX',
        'Feldborg BMX',
        'Filskov Cykel Klub',
        'Fjends Motionscykelklub',
        'Fjordager Idrætsforening',
        'FK 73 - Kragelund Cykelmotion',
        'FLUIF-MORS',
        'Fredericia Cycle Club',
        'Fredericia Trihjulet',
        'Frederikshøj Cycling Club',
        'Galten Cykel Klub',
        'Give Cykelklub',
        'Gl Rye MTB',
        'Gram Cykelklub',
        'Gråsten Cykelklub',
        'Grenaa Cykle Club',
        'Grindsted Cykel Motion',
        'Haderslev BMX-klub',
        'Haderslev Starup Cykelklub',
        'Hald Ege – Ravnstrup KFUM',
        'Hammel Cykle Klub',
        'Hammerum Gjellerup Cykelklub',
        'Hedensted Cykel Klub',
        'Herning Cykle Klub',
        'HMIF (Hoptrup-Marstrup Idrætsforening)',
        'Hobro Cykle Club af 1938',
        'Holstebro Cycleclub af 1960',
        'Holstebro Cykelmotion af 1994',
        'Holsted Cykel Motion',
        'Horsens Amatør Cykleklub',
        'Hurup Thy Cykel Motion',
        'Ikast Atletik- og Motionsforening',
        'Ikast BMX Klub',
        'Ilbro-Lørslev Idrætsforening',
        'Jegerup Omegns Cykelklub (JOCK)',
        'Jernbanernes Idrætsforening Århus',
        'KÆDEN Nr Lyndelse',
        'Kerteminde Cykelklub',
        'Kjellerup Cykelklub',
        'Knaber Cyklisterne',
        'Kolding Bicycle Club',
        'Korup-Motion-Cykling (Korup IF)',
        'Le Pedaleur De Charme',
        'Lemvig Cykle Klub',
        'Linak Cykleklub',
        'Løgstør Håndboldklub',
        'Mejrup Cykleclub',
        'Middelfart Cykel Club',
        'Midtfyns Cykle Club',
        'miKKen Cycling',
        'Møldrup BMX Klub',
        'Morsø Cykel Klub',
        'Motionscykelklubben Himmerland',
        'Motionscykelklubben Ringe Cykelklub',
        'Motionscykle Klubben Baghjulet',
        'Mountain Bike Klub Silkeborg',
        'Mountainbike Club Vejle',
        'MTB 6000',
        'MTB Esbjerg',
        'MTB Frederikshavn',
        'MTB Kolding',
        'MTB Randers',
        'MTB Sønderborg',
        'Multi Motion Assens',
        'Næsby Cykel Motion',
        'Nibe Motions Cykel Club',
        'Nordjysk Bicycle Club - Frederikshavn Motion',
        'Notmark Sogns Ungdomsforening',
        'Nr Hostrup Ungdomsforening',
        'Nr Søby Cykel Klub',
        'Nyborg Cykle Klub',
        'Odder Cykel Klub',
        'Odense Cycling Masters',
        'Odense Triathlon Klub - Motion',
        'Oksbøl Cykel Team',
        'Ølgod Cykelmotion',
        'Ølsted Cykelmotion',
        'Østjysk BMX',
        'Østsalling Idrætsforening',
        'Pandrup Mountainbike Klub',
        'Politiets Idrætsforening, Århus',
        'Racing Bjerringbro',
        'Racing Kolding',
        'Racing89ers',
        'Randers BMX',
        'Randers Cykelmotion',
        'Randers Cykleklub af 1910',
        'Ribe Cycle Club',
        'Ringkøbing Cykle Club',
        'Rødekro Cykle Club RKCC',
        'Rold Skov MTB',
        'Ry CC',
        'Sæby Motions Cykel Club',
        'Sallingsund Cykelmotion',
        'Saltum Trim',
        'Sidevinden',
        'Silkeborg Cr Motion',
        'Silkeborg IF Cykling',
        'Skanderborg BMX Klub',
        'Skanderborg Cykleklub',
        'Skive Cykle Klub',
        'Skjern Gymnastikforening af 1916',
        'Snedsted GIF – Motionsforening',
        'Snejbjerg Cykelmotion',
        'Solbjerg IF Cycling',
        'Sønderborg Cykle Klub',
        'Søvind Cykel-Motion',
        'Stjær e-Cycling',
        'Støvring Motions Cykleklub',
        'Strada Cycling',
        'Struer Cykelklub',
        'Sunds Cykelmotion',
        'Svendborg Cykle Club',
        'Svendborg Mountainbike Klub',
        'Sydbyens Cykelklub Kolding',
        'Tarp Cykel-Motion',
        'Team 9280',
        'Team Asmussen Cykling',
        'Team Egtved',
        'Team Hjallerup',
        'Team Taasinge',
        'Testrup Mårslet Gymnastikforening',
        'Thy BMX',
        'Thy Cykle Ring',
        'Tistrup Cykelmotion',
        'Tjæreborg Cycling',
        'Tjørring Cykelmotion',
        'Toftlund Cykelmotion',
        'Tønder Amatør Cykle Ring',
        'Tønder BMX',
        'Tønder Cykle Motion - TCM',
        'TSIF Cykling - Taulov BMX',
        'TST Tilst Cykling',
        'Varde BMX',
        'Varde Cykelklub',
        'Vejen Bicycle Club',
        'Vejgaard Cykelmotion',
        'Vejle Cykel Klub',
        'Vejle Cykel Motion',
        'Velo Cycling Club',
        'Viborg MTB',
        'Viborg Trial Klub',
        'Vodskov Motions Cykel Club',
    ],
    'Distrikt Sjælland' => [
        'ABC København',
        'Allerød Cykle Klub',
        'Allerød Orienteringsklub',
        'Amager Cykle Ring',
        'Audax Randonneurs Danemark',
        'Birkerød Bicycle Club',
        'Boldklubben Frem Sakskøbing',
        'Bornholms Cycle Club',
        'Brandvæsenets Idrætsforening',
        'Brøndby Cykel Motion',
        'BSR-Cykelmotion',
        'CK Kronborg',
        'CK Nordsjælland',
        'Copenhagen Virtual Cycling (Grøndal MultiCent',
        'Cycling Club Hillerød (CC Hillerød)',
        'Cykleklubben Fix Rødovre',
        'Cykleklubben Viking',
        'Danish Zwift Racers',
        'Dansk Mountainbike Klub',
        'DBC Ballerup',
        'Den Blå Mur',
        'Distrikt Sjælland Moderklub',
        'Dragør Cykelklub',
        'FIF Atletik og Motion',
        'FL Smidth-Cykelmotion',
        'Frederiksværk Motions Cykelklub',
        'Frederiksberg Bane-& Landevejsklub',
        'Furesø Cykle Club',
        'Gentofte CC',
        'Greve Cykle Club',
        'Gribskov Cykel Motion',
        'Hareskov Cykelklub (Team Hareskov Cykler af 2',
        'Haslev Cykelmotion',
        'Hillerød MTB Klub',
        'Holbæk Cykelsport',
        'Holbæk Trial Klub',
        'Holte MTB Klub',
        'Hvidovre Cykle Klub',
        'Hvidovre Trail',
        'Ishøj Motion Cykle Club',
        'Johnny Cash Cykelklub',
        'K C K Herlev',
        'Kalundborg BMX klub',
        'Kalundborg Cykle Club',
        'Kirke Hyllinge Cykelmotion',
        'Klampenborg CC',
        'Københavns BMX Klub',
        'Køge BMX Klub',
        'Køge Cykel Ring',
        'Lolland-Falster Cykle Klub',
        'Lyngby Cycle Club',
        'Motionscykelklubben i Skævinge Komm',
        'Motionscykelklubben Ventoux',
        'Næstved Bicycle Club',
        'Næstved Cykel-Motion',
        'Nakskov Cykle Club',
        'Nexø Motion Cykel Club',
        'Nørrebro Cykleklub',
        'Nykøbing Sjælland Cykelmotion',
        'Ølsemagle Motion',
        'Ølstykke Cykle Klub',
        'Ordrup Cykle Club',
        'Pedal-Atleterne Fredensborg',
        'Politiets IF Kbh-Cykling',
        'Rigspolitiets Idrætsforening (RPIF)',
        'Ringsted Motionsklub',
        'Rønnede If Cykelmotion',
        'Roskilde BMX Klub',
        'Roskilde Cykel Motion',
        'Roskilde Cykle Ring',
        'Roskilde Mountainbike Klub',
        'SCC - Skrænten Cyclecross Club',
        'SCC Zealand',
        'SemiProTour',
        'Skiklubben Hareskov',
        'Slagelse Cykle Ring',
        'Slagelse Cykle Ring Motion',
        'Slagelse MTB',
        'Slangerup Cykel Klub',
        'Sorø Bicycle Club',
        'Sorø BMX',
        'Stevns MTB',
        'Sydkystens Cycling',
        'Sydhavs BMX',
        'Taastrup TIK - Motionscykling',
        'Team Compendium',
        'Team Cycling Ringsted',
        'Tryg Cykelforening',
        'Ulkestrup Cycling Club ("UCC")',
        'Værløse-Farum Cykleklub',
        'VHG Cykelsport',
        'Vordingborg Motions Cykleklub',
    ]
];
